# Generated by Django 3.2.2 on 2024-02-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
