# Generated by Django 3.2.2 on 2024-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_order_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
