# Generated by Django 3.2.2 on 2024-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_aperturacaja_caja_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturacaja',
            name='caja_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
